model: &DEFAULT

  # Directory setup
  fig_dir: '../figures/2021/'
  data_dir: 'data/'
  output_dir: 'outputs/'
  model_dir: 'outputs/tensorflow_models/'
  param_dir: 'outputs/params/'
  log_dir: 'logs/'
  
  train_data_file: 'data/train_data_kfold0.npy'
  test_data_file: 'data/test_data_kfold0.npy'
  kfold: 0
  colorlaw_file: 'data/F99_colorlaw.txt'

  #out_file_tail: 'test'
  #posterior_file_tail: 'test'
  out_file_tail: '_3stage_train_decorrelate_all' #_magnitude_twinscut_huber' #_maxlight' #_1e-3clip'
  posterior_file_tail: '_3stage_train_decorrelate_all_longchain' #_lonchain_newinit' #_magnitude_twinscut_huber' #_maxlight' #longchain' #_1e-3clip'

  #out_file_tail: '_minz_0pt02_data_augment_decorrelatedust_adamw_elu'
  #posterior_file_tail: '_minz_0pt02_data_augment_decorrelatedust_adamw_elu'
  
  # Outputs
  model_summary: !!bool True
  savefig: !!bool False
  savemodel: !!bool True  
  print_params: !!bool True
  
  # Data dimensionality
  data_dim: 288
  cond_dim: 1 
  n_timestep: 32

  # AE model architecture
  encode_dims: [256, 128, 32]
  decode_dims: [32, 128, 256]
  #encode_dims: [64, 32, 16]
  #decode_dims: [16, 32, 64]
  #encode_dims: [8, 16, 8]
  #decode_dims: [8, 8, 1]
  #encode_dims: [16, 8, 4]
  #decode_dims: [4, 8, 16]
  #latent_dims: [0,1,2,3]#[6,7,8]
  latent_dims: [0] #3,0,1,2,4] #,3]#,4,5]

  physical_latent: !!bool True
  colorlaw_preset: !!bool True
  use_amplitude: !!bool True

  # cuts here only effect measured model uncertainty. posterior analysis still performed on all SN
  min_train_redshift: !!float 0.02
  max_train_redshift: !!float 1.0
  max_light_cut: [-10, 40]  # don't train on SN without at least 1 spectra within this range [units = days]
  max_light_cut_spectra: [-10, 40]  # don't train on SN without at least 1 spectra within this range [units = days]
  twins_cut: !!bool False # Cut data that was not used in the Twins analysis (https://arxiv.org/abs/2105.02676)

  # Flow architecture
  nlayers: 12
  nunit: 8
  batchnorm: !!bool False

posterior:
  <<: *DEFAULT

  nchains: 30

  # Find MAP using lbfgs minimizer
  find_MAP: !!bool True
  stop_ratio: 0.0001
  max_iterations: 2500 #2500
  max_line_search_iterations: 50
  tolerance: 0.01

  # Run HMC
  run_HMC: !!bool True
  ihmc: !!bool True # True if HMC, false if MCMC
  num_burnin_steps: 5000 #25000
  num_samples: 100000 #25000
  num_leapfrog_steps: 5
  step_size: 0.001
  target_accept_rate: 0.651 # modifies step size to try to reach this target

  seed: 13579  
  batch_size: 171
  
  train_noise: !!bool False        # resample data within measurement errors
  vary_mask: !!bool False           # mask <mask_vary_frac> of spectra for each SN

  lr: !!float 0.001
  noise_scale: !!float 1.0 
  mask_vary_frac: !!float 0.2

  rMAPini: !!bool False            # Use encoder or random MAP position to start gradient descent

  train_MAP: !!bool True
  train_amplitude: !!bool True     # Free amplitude parameter. Don't train if use_amplitude==True in network 
  train_dtime: !!bool True         # Delta time shift for t0
  train_bias: !!bool False         # Additive bias
  
  savedata: !!bool True



